---
 - name: Install_Dep_For_Docker
   yum: name={{ item }}
   with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
   become: yes

 - name: Add Docker Repo in RHEL/CentOS
   get_url:
     url: https://download.docker.com/linux/centos/docker-ce.repo
     dest: /etc/yum.repos.d/docer-ce.repo
   become: yes

 - name: Install Contaier-selinux
   command: yum install http://vault.centos.org/centos/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm -y

 - name: Install Docker
   package: name=docker-ce state={{ pkgs_state }} update_cache=yes

 - name: enable docker
   service:
     name: docker
     state: started
     enabled: yes
   become: yes
