---
- name: Install Grafana repository
  template:
    src:   Grafana.repo.j2
    dest:  /etc/yum.repos.d/grafana.repo
    owner: root
    group: root
    mode:  0644


 - name: Install
   package: name= state={{ pkgs_state }} update_cache=yes


 - name: enable_Grafana
   service:
     name: grafana-server
     state: started
     enabled: yes
   become: yes


 - name: Install firewalld on RHEL
   yum: name=firewalld state=present

 - name: Enable Port for Grafana
   firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
