---
 - name: download mysql repo
   get_url: url=https://repo.mysql.com/mysql57-community-release-el7-11.noarch.rpm dest=/tmp/mysql7.11.rpm
   tags: mysql

 - name: install mysql repo
   shell: /bin/rpm -Uvh /tmp/mysql7.11.rpm
   register: mysql_repo_result
   failed_when: "'conflict' in mysql_repo_result.stderr"
   tags: mysql

 - name: Install MYSQL
   package: name={{ item }} state={{ pkgs_state }} update_cache=yes
   with_items:
    - mysql
    - mysql-service

 - name: enable mysql
   service:
     name: mysqld
     state: started
     enabled: yes
   become: yes
