---
 - name: Update YUM
   yum:
    name: '*'
    state: latest

 - name: enable epel repo
   package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

 - name: Install Java 8
   yum: name=java-1.8.0-openjdk-devel state=present


