---
 - name: enable docker
   service:
     name: docker
     state: started
     enabled: yes
   become: yes

 - name: enable Jenkins
   service:
     name: jenkins
     state: started
     enabled: yes
   become: yes

 - name: enable mysql
   service:
     name: mysqld
     state: started
     enabled: yes
   become: yes

 - name: restart mysql
   service: name=mysqld state=restarted

 - name: enable Grafana
   service:
     name: grafana-server
     state: started
     enabled: yes
   become: yes

